### PR TITLE
Fix enable_legacy_abac issue #79

### PR DESCRIPTION
**Pull request by vscoder**
Added
```
resource "google_container_cluster" "cluster" {
  enable_legacy_abac = var.enable_legacy_abac
  ...
}
```
in file `modules/gke-cluster/main.tf` block `resource "google_container_cluster" "cluster" {...}`

fix issue #79

### CODE REVIEW

**Comment by yorinasub17** [comment]
Thanks for your contribution and apologies for the long delay in getting back to you on this! Can you rebase on master to get all the test fixes in? At that point, we should be able to get a green build to merge this in.

**Comment by vscoder** [comment]
Sorry for the long answer. Rebase is done. All tests passed.

**Comment by yorinasub17** [comment]
Thanks! Just kicked off a build.

**Comment by yorinasub17** [comment]
Ok the build passed, so will go ahead and merge this. Thanks for your contribution!

**Pull request merged**
