### PR TITLE
add enable_shielded_nodes to gke module

### PR DESCRIPTION
**Pull request by marekaf**
solves https://github.com/gruntwork-io/terraform-google-gke/issues/112

### CODE REVIEW

**Comment by robmorgan** [comment]
@marekaf This looks good to me and I think, given Google's recommendations makes sense to set it as the default. One question - how did you test this PR?

**Comment by marekaf** [comment]
> @marekaf This looks good to me and I think, given Google's recommendations makes sense to set it as the default. One question - how did you test this PR?

thanks for your review

I didn't test it. 
If you want I can set up a new GCP project and test it there.
It would make more sense to run it through github actions on the upstream, no? I'm happy to close this PR from my fork. Anybody else can take over these changes and make them as their own - I don't mind as long as this gets to the upstream:)

**Comment by Etiene** [comment]
Apologies for the delay in responding to this PR. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by MoonMoon1919** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice).

**Pull request closed without merging**
