### PR TITLE
Add vertical pod autoscaling option

### PR DESCRIPTION
**Pull request by jsirianni**
- added option to enable vertical pod autoscaling
- set vertical pod autoscaling to `true` for public and private test clusters
- tested with `go test -v -timeout 60m -run TestGKECluster`

This is a backwards compatible change. Clusters deployed with `v0.4.0` of this module have vertical autoscaling disabled, which is the default behavior for this change.

The first run with this module will give the following terraform plan for clusters deployed with v0.4.0 of this module:
```
      + vertical_pod_autoscaling {
          + enabled = false
        }
```

Despite autoscaling already being disabled, Terraform wants to apply the change anyway. The change is applied in place quickly without actually changing anything. This is only for the initial run after upgrading the module.

resolves https://github.com/gruntwork-io/terraform-google-gke/issues/83

### CODE REVIEW

**Comment by jsirianni** [comment]
Looks like the build system failed, but I am not sure it is related to this change. Let me know if I need to do anything on my end, thanks :+1:

**Comment by yorinasub17** [comment]
Gah yes you are right that it isn't related to this change. I just fixed it on master. When you get the chance, can you rebase on to master to pull the fix in? Thanks!

**Comment by jsirianni** [comment]
@yorinasub17 done :+1:

**Comment by yorinasub17** [comment]
Ok build passed, so will merge this in. Thanks for your contribution!

**Pull request merged**
