### PR TITLE
feat: Enable Workload Identity Feature

### PR DESCRIPTION
**Pull request by MeNsaaH**
Creating this because #90 is stale.

### CODE REVIEW

**Comment by robmorgan** [comment]
Thanks @MeNsaaH, are you able to:

1. Ensure this module feature is included in at least one of the examples?
2. Also ensure a test properly wraps it using [Terratest](https://terratest.gruntwork.io)?

**Comment by MeNsaaH** [comment]
> Thanks @MeNsaaH, are you able to:
> 
>     1. Ensure this module feature is included in at least one of the examples?
> 
>     2. Also ensure a test properly wraps it using [Terratest](https://terratest.gruntwork.io)?


@robmorgan, I've added it to examples. Terratest tests the examples as well. Do I have to write any extra tests for the workload identity?

**Comment by robmorgan** [comment]
@MeNsaaH No that will be fine. I was unsure if we should also add it to the other examples, but we'll leave it purely in the public cluster example for now. I've kicked off the tests in https://app.circleci.com/pipelines/github/gruntwork-io/terraform-google-gke/283/workflows/948e72f6-5b74-4f93-bb05-a8dfdf469cb4/jobs/491

**Comment by robmorgan** [comment]
Looks like the tests passed in https://app.circleci.com/pipelines/github/gruntwork-io/terraform-google-gke/283/workflows/1628e2d5-3d2b-4cd1-b1d6-5443f86eb241/jobs/493

**Pull request merged**
