### PR TITLE
Upgrade blog post example to tf12

### LINKED ISSUE #72: Following the instructions from your google blog post, and I'm getting errors
https://cloud.google.com/blog/products/devops-sre/deploying-a-production-grade-helm-release-on-gke-with-terraform

I clicked on the first "**open in google cloud shell**" button which clones this repo and has some config scripts loaded.

Following the instructions on the right side, I get to `terraform apply` and, from the error messages, it looks like the string values aren't being interpolated?

Screen Shot 2019-12-08 at 7 32 17 PM

This is my first time dabbling in Terraform (and Kubernetes), so I'm completely lost as to what's wrong.

### PR DESCRIPTION
**Pull request by autero1**
This PR upgrades the blog post example to be compatible with `terraform 0.12.x`.

Fixes #72

### CODE REVIEW

**Comment by autero1** [comment]
It should. I deployed locally and it worked. But I bumped into another issue when running in cloud shell. The latest release versions of both `terraform-google-gke` and `terraform-google-network` require `terraform 0.12.7`. But gcr.io/graphite-cloud-shell-images/terraform:latest is `0.12.6`. Any chance we could get that updated to latest `terraform` version?

**Comment by rileykarson** [comment]
Yep, I own that image. Bumping to `0.12.18`. It'll take somewhere between a day - a week to propagate, since we cache the image.

**Comment by autero1** [comment]
Thanks! Is `latest` the only tag for the image or do you tag them with specific versions, as well?

**Comment by rileykarson** [comment]
`latest` is the only tag on the image, since it's the only one considered "verified" and cached by Cloud Shell.

**Comment by autero1** [comment]
Ok. We'll then probably wait for the propagation until after Christmas. I'll check periodically to see if I can run the example in Cloud shell and merge after that.

**Comment by autero1** [comment]
Merging this in. Worked locally, will run the blog post example now

**Pull request merged**
